language: python

sudo: true

python: "3.6"

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - libltdl7-dev
      - libgsl0-dev
      - libncurses5-dev
      - libreadline6-dev
      - pkg-config
      - python-all-dev
      - python-matplotlib
      - python-numpy
      - python-scipy

before_install:
  # in before_install, we install all the NESTML dependencies

  # install antrl4
  - sudo apt install openjdk-8-jre
  - wget http://www.antlr.org/download/antlr-4.7.1-complete.jar
  - echo \#\!/bin/bash > antlr4
  - echo java -cp \"`pwd`/antlr-4.7.1-complete.jar:$CLASSPATH\" org.antlr.v4.Tool \"\$@\" >> antlr4
  - echo >> antlr4
  - chmod +x antlr4
  - export PATH=$PATH:`pwd`

  # install Python module dependencies
  - pip install --upgrade pip pytest
  - pip install -r requirements.txt

  # install latest odetoolbox from git master (N.B. GSL/PyGSL installation is skipped as NESTML ignores stiffness test result)
  - pip uninstall --yes odetoolbox
  - pip install git+https://github.com/nest/ode-toolbox.git

install:
  # in install, we install NESTML itself

  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - echo $PYTHONPATH
  - python setup.py install

before_script:
  # use antlr4 to re-generate lexer+parser
  - cd $TRAVIS_BUILD_DIR
  - find pynestml/generated -not -name __init__.py -a -not -name generated -delete
  - cd pynestml/grammars
  - ./generate_lexer_parser
  - cd ../..

stages:
  - test
  - integration

jobs:
  include:
    - stage: test
      script:
        - find /usr/lib/x86_64-linux-gnu -name "libpython3*.so"
        - find /opt/python -name "python*"
        - export PYTHON_LIB_DIR=
        # echo "pytest -s tests"

    - stage: integration
      install:
        # install nest-simulator
        - cd
        - git clone --depth=1 https://github.com/nest/nest-simulator
        - mkdir nest_install
        - cd nest_install
        - export PYTHON_INCLUDE_DIR=`python3 -c "from sysconfig import get_paths; from pprint import pprint; info = get_paths(); print(info['include'])"`
        - echo $PYTHON_INCLUDE_DIR
        - cmake -DCMAKE_INSTALL_PREFIX=~/nest_install -Dwith-python=3 -DPYTHON_LIBRARY=`find /usr/lib/x86_64-linux-gnu -name "libpython3*.so"` -DPYTHON_INCLUDE_DIRS=$PYTHON_INCLUDE_DIR ~/nest-simulator
        - echo make && make install 
                                                                
        # install NESTML itself
        - cd $TRAVIS_BUILD_DIR
        - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages
        - echo $PYTHONPATH
        - python setup.py install

      script:
        - echo `pwd`
        - nestml --input_path models/iaf_psc_exp.nestml --target_path target --suffix nestml_unit_test --logging_level INFO
        - cd target
        - ls -la ~
        - ls -la ~/nest_install
        - ls -la ~/nest_install/bin
        - cmake -Dwith-nest=/home/travis/nest_install/bin/nest-config .
        - make && make install
        - export PYNESTKERNEL_LOCATION=`find /home/travis/nest_install/lib -name pynestkernel.so`
        - export PYNESTKERNEL_LOCATION=`dirname $PYNESTKERNEL_LOCATION`
        - export PYNESTKERNEL_LOCATION=`dirname $PYNESTKERNEL_LOCATION`
        - echo $PYNESTKERNEL_LOCATION
        - export PYTHONPATH=$PYTHONPATH:$PYNESTKERNEL_LOCATION
        - python $TRAVIS_BUILD_DIR/extras/nest_integration_test.py
