language: python

sudo: true

stages:
  - test
  - integration

jobs:
  include:
    - stage test:
      script: pytest -s tests
    - stage integration:
      install:
        - pip install matplotlib
        - cd ~ && git clone https://github.com/nest/nest-simulator nest_source
        - mkdir nest_install
        - cd nest_source && mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=~/nest_install .. && make && make install
        - cd $TRAVIS_BUILD_DIR
      script:
        - echo "Hello, world!"

    
