language: python

sudo: true

python:
  - "3.5"
  - "3.6"

before_install:
  # in before_install, we install all the NESTML dependencies

  # install antrl4
  - sudo apt install openjdk-8-jre
  - wget http://www.antlr.org/download/antlr-4.7.1-complete.jar
  - echo \#\!/bin/bash > antlr4
  - echo java -cp \"`pwd`/antlr-4.7.1-complete.jar:$CLASSPATH\" org.antlr.v4.Tool \"\$@\" >> antlr4
  - echo >> antlr4
  - chmod +x antlr4
  - export PATH=$PATH:`pwd`

  # install Python module dependencies
  - pip install --upgrade pip pytest
  - pip install -r requirements.txt

  # install latest odetoolbox from git master (N.B. GSL/PyGSL installation is skipped as NESTML ignores stiffness test result)
  - pip uninstall --yes odetoolbox
  - pip install git+https://github.com/nest/ode-toolbox.git

install:
  # in install, we install NESTML itself

  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - echo $PYTHONPATH
  - python setup.py install

  #- python PyNestML.py -path models -target target
  #- cd ../target && mkdir build && cd build
  #- cmake -Dwith-nest=~/nest_install/bin/nest-config .. && make && make install
  #- cd $TRAVIS_BUILD_DIR
  #- source $TRAVIS_BUILD_DIR/nest_install/bin/nest_vars.sh

before_script:
  # use antlr4 to re-generate lexer+parser
  - find pynestml/generated -not -name __init__.py -a -not -name generated -delete
  - cd pynestml/grammars
  - ./generate_lexer_parser
  - cd ../..

stages:
  - test
  - integration

jobs:
  include:
    - stage: test
      script: echo "foo"
    - stage: integration
      script: echo "bar"
